name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install ESLint
        run: npm install -g eslint
      - name: Install Python tools
        run: |
          pip install ruff mypy
      - name: Ruff check
        run: ruff check .
      - name: Ruff format
        run: ruff format --check .
      - name: Mypy
        run: mypy .
      - name: Functional test
        run: python main.py .
      - name: JS syntax
        run: node --check script.js
      - name: ESLint
        run: eslint script.js
